version: "3.8"

services:
  postgres:
    image: postgres:12.8
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=abc@1234
      - POSTGRES_DB=dbexperiment
    volumes:
      - ../localdata/postgres:/var/lib/postgresql/data
      - ../:/dbexperiment