version: "3.8"

services:
  python:
    build:
      context: ../
      dockerfile: deploy/DockerfilePython
    volumes:
      - ../data_tools:/data_tools
      - ../data:/data
  postgres:
    build:
      context: ../
      dockerfile: deploy/DockerfilePostgre
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=abc@1234
      - POSTGRES_DB=dbexperiment
    volumes:
      - ../localdata/postgres:/var/lib/postgresql/data
      - ../data:/data
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.2
    environment:
      - discovery.type=single-node
    volumes:
      - ../localdata/elasticsearch:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
  mongo:
    image: mongo:5
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: abc@1234
      MONGO_INITDB_DATABASE: dbexperiment
    volumes:
      - ../data:/data
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
  neo4j:
    image: neo4j:4.3
    volumes:
      - ../localdata/neo4j/data:/data
      - ../data:/_data
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G